name: Fanatik IPTV Güncelleyici

on:
  push:
    branches:
      - main
  schedule:
    # Her 30 dakikada bir çalıştır (Tokenler hızlı değiştiği için sık çalışmalı)
    - cron: '*/30 * * * *'
  workflow_dispatch: # Manuel tetikleme butonu ekler

jobs:
  scrape_and_update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Depoyu Çek (Checkout)
        uses: actions/checkout@v3

      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kütüphaneleri Yükle
        run: |
          pip install -r requirements.txt

      - name: Botu Çalıştır
        run: python main2.py

      - name: Değişiklikleri Kaydet ve Gönder
        run: |
          git config --global user.name "FanatikBot"
          git config --global user.email "actions@github.com"
          git add data.json
          # Eğer değişiklik yoksa hata verme, varsa commit yap
          git diff --quiet && git diff --staged --quiet || (git commit -m "Canlı yayınlar güncellendi: $(date)" && git push)
