name: Mac Verisi Cek

on:
  workflow_dispatch:      # Butona basınca çalışması için
  schedule:
    - cron: '*/30 * * * *' # Her 30 dakikada bir otomatik çalışması için

permissions:
  contents: write         # JSON dosyasını repoya kaydetmek için izin

jobs:
  veri-cekme-isleri:
    runs-on: ubuntu-latest

    steps:
      - name: Kodları İndir (Checkout)
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Gerekli Kütüphaneyi Kur
        run: pip install requests

      - name: Scripti Çalıştır
        run: python main2.py

      - name: Sonuçları Kaydet (Git Push)
        run: |
          git config --global user.name "Bot"
          git config --global user.email "bot@github.com"
          git add canli_yayinlar.json
          git commit -m "Veriler güncellendi" || echo "Değişiklik yok"
          git push
