name: S Sport Otomatik Bot

on:
  workflow_dispatch:      # Butona basınca çalıştır
  schedule:
    - cron: '0 */2 * * *' # Her 2 saatte bir çalıştır

permissions:
  contents: write

jobs:
  veri-guncelle:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu Çek
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kütüphaneleri Yükle
        run: pip install -r requirements.txt

      - name: Scripti Çalıştır
        run: python main.py

      - name: Sonucu Kaydet (Push)
        run: |
          git config --global user.name "S Sport Bot"
          git config --global user.email "bot@github.com"
          git add canli_yayinlar.json
          git commit -m "Otomatik güncelleme: $(date)" || echo "Değişiklik yok"
          git push
